backend/apps/blog_web/lib/blog_web/router.ex
defmodule BlogWeb.Router do
  use BlogWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :put_root_layout, {BlogWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BlogWeb do
    pipe_through :browser

    get "/", PostsController, :home

    get "/posts", PostsController, :index
    get "/posts/:title", PostsController, :show

    get "/rss", RssController, :index
  end
end

backend/apps/blog_web/lib/blog_web/controllers/posts_controller.ex
defmodule BlogWeb.PostsController do
  use BlogWeb, :controller

  alias Blog.Posts
  alias Blog.Posts.Post

  def index(conn, %{"tag" => tag}) do
    with {:ok, posts} <- Posts.list_posts_with_tag(tag) do
      conn
      |> assign(:posts, posts)
      |> assign(:tag, tag)
      |> render("index.html")
    end
  end

  def index(conn, _params) do
    with {:ok, posts} <- Posts.list_posts() do
      conn
      |> assign(:posts, posts)
      |> assign(:tag, nil)
      |> render("index.html")
    end
  end

  def show(conn, %{"title" => title}) do
    with {:ok, %Post{} = post} <- Posts.get_post_by_title(title),
         {:ok, %Post{} = post} <- Posts.process_internal_links(post) do
      conn
      |> assign(:post, post)
      |> assign(:show_list_button, true)
      |> render("show.html")
    end
  end

  def home(conn, _params) do
    with {:ok, %Post{} = post} <- Posts.get_post_by_id(1),
         {:ok, %Post{} = post} <- Posts.process_internal_links(post) do
      conn
      |> assign(:post, post)
      |> assign(:show_list_button, false)
      |> render("show.html")
    end
  end
end

backend/apps/blog_web/lib/blog_web/controllers/rss_controller.ex
defmodule BlogWeb.RssController do
  use BlogWeb, :controller
  plug :put_root_layout, false

  alias Blog.Posts

  def index(conn, _params) do
    with {:ok, posts} <- Posts.list_posts() do
      conn
      |> assign(:posts, posts)
      |> render("index.xml")
    end
  end
end

backend/apps/blog_web/lib/blog_web/views/error_view.ex
defmodule BlogWeb.ErrorView do
  use BlogWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

backend/apps/blog_web/lib/blog_web/views/layout_view.ex
defmodule BlogWeb.LayoutView do
  use BlogWeb, :view

  def page_title(%Plug.Conn{assigns: %{posts: _posts}}) do
    " · All Posts"
  end

  def page_title(%Plug.Conn{assigns: %{post: %{title: title}}}) do
    " · #{title}"
  end

  def page_title(_conn) do
    ""
  end
end

backend/apps/blog_web/lib/blog_web/views/posts_view.ex
defmodule BlogWeb.PostsView do
  use BlogWeb, :view

  def list_view_title(nil, _posts) do
    "All Posts"
  end

  def list_view_title(_label, []) do
    "Oops! There isn't anything here."
  end

  def list_view_title(label, posts) do
    # De-downcase the labels which come in through
    # URLs by finding the equivalent label in
    # all posts being shown.
    known_labels =
      posts
      |> Enum.flat_map(& &1.tags)
      |> Enum.uniq()
      |> Map.new(&{String.downcase(&1), &1})

    case known_labels[label] do
      nil -> "Oops! There isn't anything here."
      label -> "All #{label} Posts"
    end
  end
end

backend/apps/blog_web/lib/blog_web/templates/layout/app.html.eex
<%= @inner_content %>

backend/apps/blog_web/lib/blog_web/templates/layout/live.html.leex
<%= @inner_content %>

backend/apps/blog_web/lib/blog_web/templates/posts/index.html.eex
<h1><%= list_view_title(@tag, @posts) %></h1>
<%= if @posts == [] do %>
  <p>
  Unfortunately, there are no posts to display matching the requested criterion.
  </p>
  <p>
    <a href="/posts">Show all posts instead? →</a>
  </p>
<% else %>
  <ul class="post-list">
    <%= for post <- @posts do %>
      <li>
        <a href="/posts/<%= post.normalized_title %>">
          <%= post.title %>
        </a>
        <time><%= Timex.format!(post.created_at, "%h %d, %Y", :strftime) %></time>
        <div class="labels">
          <%= for tag <- post.tags do %>
            <a class="post-label" href="/posts?tag=<%= String.downcase(tag) %>">
              <%= String.downcase(tag) %>
            </a>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

backend/apps/blog_web/lib/blog_web/templates/posts/show.html.eex
<%= if @show_list_button do %>
<label class="subheading">
  <em>Approx. <%= @post.reading_time_minutes %> minute reading time</em>
</label>
<% end %>

<%= raw @post.content %>

<%= if @show_list_button do %>
<p>
  <br>
  <a href="/posts">Return to Posts →</a>
</p>
<% end %>

backend/apps/blog_web/lib/blog_web/templates/rss/index.xml.eex
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <% now = DateTime.utc_now() %>
  <% rfc_822 =  "%a, %d %b %Y %H:%M:%S UT" %>
  <% all_tags = @posts
       |> Enum.flat_map(& &1.tags)
       |> Enum.uniq()
       |> Enum.sort()
       |> Enum.join("/") %>
  <channel>
    <title>Chris Bailey's blog</title>
    <link><%= Routes.posts_url(@conn, :index) %></link>
    <atom:link href="<%= Routes.rss_url(@conn, :index) %>" rel="self" type="application/rss+xml" />
    <description>
      A collection of my thoughts, oftentimes programming related. I primarily dabble in Erlang/Elixir programming,
      or describing various things around programming languages, development environments, and operating systems.
    </description>
    <language>en</language>
    <copyright>Copyright <%= now.year %> Chris Bailey</copyright>
    <lastBuildDate><%= Calendar.strftime(now, rfc_822) %></lastBuildDate>
    <category><%= all_tags %></category>
    <ttl><%= 60 * 24 %></ttl>
    <%= for post <- @posts do %>
      <item>
        <title><%= post.title %></title>
        <link><%= Routes.posts_url(@conn, :show, post.normalized_title) %></link>
        <guid><%= Routes.posts_url(@conn, :show, post.normalized_title) %></guid>
        <description><![CDATA[ <%= post.description %> ]]></description>
        <%= for tag <- post.tags do %>
          <category><%= tag %></category>
        <% end %>
        <pubDate><%= Calendar.strftime(post.created_at, rfc_822) %></pubDate>
      </item>
    <% end %>
  </channel>
</rss>